### ISSUE TITLE
AutoRest NuGet Package Generator Build Step not available after installation

### ISSUE THREAD

**Issue by ChristophRichner** [eShopWorld/vsts-autorest#4]
I would like to try out this extension. I've already tried in two different Azure DevOps Account. In both accounts I was able to install the extension.

But after creating a new build template the step can't be found by name inside the _Add tasks_ dialog.

Strange enough is listed in the lower Marketplace section as already _Installed_

![image](https://user-images.githubusercontent.com/43644394/48437258-1b52aa80-e781-11e8-86f8-7127650d13a4.png)

What do I miss? Anyone facing the same issue?

**Comment by VaclavK** [comment]
@ChristophRichner we use this extensively in-house..... the task is release level task - the use case being that as you release the app (into whatever environment - typically CI  - and after you vet it with some tests, you generate the client nugget to enable integrations with the new deploy of the service when it is deployed to higher environments..

from task manifest -   "visibility": [ "Release" ],


<img width="427" alt="image" src="https://user-images.githubusercontent.com/3881864/48445896-ad61af80-e78f-11e8-8520-a68994ca13c3.png">
<img width="491" alt="image" src="https://user-images.githubusercontent.com/3881864/48445936-c4080680-e78f-11e8-8e3c-2f96b3df8373.png">

what is your scenario?

**Comment by ChristophRichner** [comment]
I see. Any reason why this task should be limited to release?

**Comment by VaclavK** [comment]
referring to above, this is a philosophical and technical choice

 - when you're building your project, you do not know whether it will pass your quality checks yet and these do typically involve integration level tests - for those you need the service to be stood up
- for the service to be stood up - so that you can even hit the Autorest middleware (to get the swagger json) -  you would generally deploy it = again, this is release (you would not want to run the service on a build node...)

what kind of flow do you have in mind?

**Comment by ChristophRichner** [comment]
We use an API-First Approach with OpenAPI 2.0 aka Swagger. Each API change results in an Pull Request which gets reviewed. If everything is looking good the PR gets approved.

To bring the approved changes to life we generate the API & Client classes. Say after the Pull Request gets merged into our develop (GitFlow) branch we're in need for the new client. Typically the first consumer of the Client Package are our very own Unit Tests to build the API in a Test Driven manner.

Does this make sense to you?

**Comment by VaclavK** [comment]
@ChristophRichner mea culpa, this completely escaped my attention... almost certainly no longer relevant to you I assume?

**Comment by ChristophRichner** [comment]
Right..
